apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.application }}
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5540
  selector:
    app: redisinsight
  type: ClusterIP
