{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.certificate.name }}
  dnsNames:
  {{- range .Values.certificate.dnsNames }}
  - {{ . }}
  {{- end }}
  issuerRef:
    name: letsencrypt-{{ .Values.letsencrypt.environment }}
    kind: ClusterIssuer
{{- end }}
