apiVersion: v2
name: nginx-ingress
description: NGINX Ingress Controller wrapper for Kind cluster
type: application
version: 0.1.0
appVersion: "1.12.0"

dependencies:
  - name: ingress-nginx
    version: 4.12.0
    repository: https://kubernetes.github.io/ingress-nginx
