apiVersion: v2
name: cert-manager
description: cert-manager for automatic TLS certificate management
type: application
version: 1.0.0
appVersion: "v1.16.2"
dependencies:
  - name: cert-manager
    version: v1.16.2
    repository: https://charts.jetstack.io
