apiVersion: v2
appVersion: "0.25.0"
description: sealed-secrets
name: sealed-secrets
version: 1.0.0
dependencies:
  - name: sealed-secrets
    version: "2.14.2"
    repository: "https://bitnami-labs.github.io/sealed-secrets/"
